package edu.unbosque.model;

// Generated 8/04/2013 03:56:28 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Faculties generated by hbm2java
 */
@Entity
@Table(name = "faculties", catalog = "semillero")
public class Faculties implements java.io.Serializable {

	private Integer idFaculty;
	private String name;
	private Set<Programs> programses = new HashSet<Programs>(0);

	public Faculties() {
	}

	public Faculties(String name, Set<Programs> programses) {
		this.name = name;
		this.programses = programses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_faculty", unique = true, nullable = false)
	public Integer getIdFaculty() {
		return this.idFaculty;
	}

	public void setIdFaculty(Integer idFaculty) {
		this.idFaculty = idFaculty;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "faculties")
	public Set<Programs> getProgramses() {
		return this.programses;
	}

	public void setProgramses(Set<Programs> programses) {
		this.programses = programses;
	}

}
