package edu.unbosque.model;

// Generated 8/04/2013 03:56:28 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Groups generated by hbm2java
 */
@Entity
@Table(name = "groups", catalog = "semillero")
public class Groups implements java.io.Serializable {

	private int idGroup;
	private Roles roles;
	private String name;
	private Set<Users> userses = new HashSet<Users>(0);

	public Groups() {
	}

	public Groups(int idGroup, Roles roles, String name) {
		this.idGroup = idGroup;
		this.roles = roles;
		this.name = name;
	}

	public Groups(int idGroup, Roles roles, String name, Set<Users> userses) {
		this.idGroup = idGroup;
		this.roles = roles;
		this.name = name;
		this.userses = userses;
	}

	@Id
	@Column(name = "id_group", unique = true, nullable = false)
	public int getIdGroup() {
		return this.idGroup;
	}

	public void setIdGroup(int idGroup) {
		this.idGroup = idGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Roles_id_rol", nullable = false)
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "groups_has_users", catalog = "semillero", joinColumns = { @JoinColumn(name = "Groups_id_group", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Users_id_user", nullable = false, updatable = false) })
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
