package edu.unbosque.model;

// Generated 8/04/2013 03:56:28 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name = "news", catalog = "semillero")
public class News implements java.io.Serializable {

	private int idNews;
	private Semilleros semilleros;
	private Users users;
	private String title;
	private String body;
	private String imagePath;
	private Date creationDate;

	public News() {
	}

	public News(int idNews, Semilleros semilleros, Users users, String title,
			String body, String imagePath) {
		this.idNews = idNews;
		this.semilleros = semilleros;
		this.users = users;
		this.title = title;
		this.body = body;
		this.imagePath = imagePath;
	}

	public News(int idNews, Semilleros semilleros, Users users, String title,
			String body, String imagePath, Date creationDate) {
		this.idNews = idNews;
		this.semilleros = semilleros;
		this.users = users;
		this.title = title;
		this.body = body;
		this.imagePath = imagePath;
		this.creationDate = creationDate;
	}

	@Id
	@Column(name = "id_news", unique = true, nullable = false)
	public int getIdNews() {
		return this.idNews;
	}

	public void setIdNews(int idNews) {
		this.idNews = idNews;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Semilleros_id_semillero", nullable = false)
	public Semilleros getSemilleros() {
		return this.semilleros;
	}

	public void setSemilleros(Semilleros semilleros) {
		this.semilleros = semilleros;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Users_id_user", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "title", nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "body", nullable = false, length = 45)
	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	@Column(name = "imagePath", nullable = false, length = 45)
	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

}
