package edu.unbosque.model;

// Generated 8/04/2013 03:56:28 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Permissions generated by hbm2java
 */
@Entity
@Table(name = "permissions", catalog = "semillero")
public class Permissions implements java.io.Serializable {

	private String idPermission;
	private String name;
	private String description;
	private Set<Roles> roleses = new HashSet<Roles>(0);

	public Permissions() {
	}

	public Permissions(String idPermission, String name, String description) {
		this.idPermission = idPermission;
		this.name = name;
		this.description = description;
	}

	public Permissions(String idPermission, String name, String description,
			Set<Roles> roleses) {
		this.idPermission = idPermission;
		this.name = name;
		this.description = description;
		this.roleses = roleses;
	}

	@Id
	@Column(name = "id_permission", unique = true, nullable = false, length = 16)
	public String getIdPermission() {
		return this.idPermission;
	}

	public void setIdPermission(String idPermission) {
		this.idPermission = idPermission;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "roles_has_permissions", catalog = "semillero", joinColumns = { @JoinColumn(name = "Permissions_id_permission", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Roles_id_rol", nullable = false, updatable = false) })
	public Set<Roles> getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set<Roles> roleses) {
		this.roleses = roleses;
	}

}
