package edu.unbosque.model;

// Generated 8/04/2013 03:56:28 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Programs generated by hbm2java
 */
@Entity
@Table(name = "programs", catalog = "semillero")
public class Programs implements java.io.Serializable {

	private Integer idProgram;
	private Faculties faculties;
	private String name;
	private Set<Users> userses = new HashSet<Users>(0);

	public Programs() {
	}

	public Programs(Faculties faculties) {
		this.faculties = faculties;
	}

	public Programs(Faculties faculties, String name, Set<Users> userses) {
		this.faculties = faculties;
		this.name = name;
		this.userses = userses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_program", unique = true, nullable = false)
	public Integer getIdProgram() {
		return this.idProgram;
	}

	public void setIdProgram(Integer idProgram) {
		this.idProgram = idProgram;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Faculties_id_faculty", nullable = false)
	public Faculties getFaculties() {
		return this.faculties;
	}

	public void setFaculties(Faculties faculties) {
		this.faculties = faculties;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "programs")
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
