package edu.unbosque.model;

// Generated 8/04/2013 03:56:28 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Researchareas generated by hbm2java
 */
@Entity
@Table(name = "researchareas", catalog = "semillero")
public class Researchareas implements java.io.Serializable {

	private Integer idResearcharea;
	private String name;
	private Set<Semilleros> semilleroses = new HashSet<Semilleros>(0);

	public Researchareas() {
	}

	public Researchareas(String name, Set<Semilleros> semilleroses) {
		this.name = name;
		this.semilleroses = semilleroses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_researcharea", unique = true, nullable = false)
	public Integer getIdResearcharea() {
		return this.idResearcharea;
	}

	public void setIdResearcharea(Integer idResearcharea) {
		this.idResearcharea = idResearcharea;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "semilleros_has_researchareas", catalog = "semillero", joinColumns = { @JoinColumn(name = "ResearchAreas_id_researcharea", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Semilleros_id_semillero", nullable = false, updatable = false) })
	public Set<Semilleros> getSemilleroses() {
		return this.semilleroses;
	}

	public void setSemilleroses(Set<Semilleros> semilleroses) {
		this.semilleroses = semilleroses;
	}

}
