package edu.unbosque.model;

// Generated 8/04/2013 03:56:28 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Roles generated by hbm2java
 */
@Entity
@Table(name = "roles", catalog = "semillero")
public class Roles implements java.io.Serializable {

	private int idRol;
	private String name;
	private Set<Permissions> permissionses = new HashSet<Permissions>(0);
	private Set<Groups> groupses = new HashSet<Groups>(0);

	public Roles() {
	}

	public Roles(int idRol, String name) {
		this.idRol = idRol;
		this.name = name;
	}

	public Roles(int idRol, String name, Set<Permissions> permissionses,
			Set<Groups> groupses) {
		this.idRol = idRol;
		this.name = name;
		this.permissionses = permissionses;
		this.groupses = groupses;
	}

	@Id
	@Column(name = "id_rol", unique = true, nullable = false)
	public int getIdRol() {
		return this.idRol;
	}

	public void setIdRol(int idRol) {
		this.idRol = idRol;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "roles_has_permissions", catalog = "semillero", joinColumns = { @JoinColumn(name = "Roles_id_rol", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Permissions_id_permission", nullable = false, updatable = false) })
	public Set<Permissions> getPermissionses() {
		return this.permissionses;
	}

	public void setPermissionses(Set<Permissions> permissionses) {
		this.permissionses = permissionses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roles")
	public Set<Groups> getGroupses() {
		return this.groupses;
	}

	public void setGroupses(Set<Groups> groupses) {
		this.groupses = groupses;
	}

}
