package edu.unbosque.model;

// Generated 8/04/2013 03:56:28 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * Semilleroattachments generated by hbm2java
 */
@Entity
@Table(name = "semilleroattachments", catalog = "semillero")
public class Semilleroattachments implements java.io.Serializable {

	private int idSemilleroAttachment;
	private Integer version;
	private Semilleros semilleros;
	private Date creationDate;
	private String name;
	private String attachmentPath;

	public Semilleroattachments() {
	}

	public Semilleroattachments(int idSemilleroAttachment,
			Semilleros semilleros, Date creationDate, String name,
			String attachmentPath) {
		this.idSemilleroAttachment = idSemilleroAttachment;
		this.semilleros = semilleros;
		this.creationDate = creationDate;
		this.name = name;
		this.attachmentPath = attachmentPath;
	}

	@Id
	@Column(name = "id_semilleroAttachment", unique = true, nullable = false)
	public int getIdSemilleroAttachment() {
		return this.idSemilleroAttachment;
	}

	public void setIdSemilleroAttachment(int idSemilleroAttachment) {
		this.idSemilleroAttachment = idSemilleroAttachment;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Semilleros_id_semillero", nullable = false)
	public Semilleros getSemilleros() {
		return this.semilleros;
	}

	public void setSemilleros(Semilleros semilleros) {
		this.semilleros = semilleros;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creationDate", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "attachmentPath", nullable = false, length = 45)
	public String getAttachmentPath() {
		return this.attachmentPath;
	}

	public void setAttachmentPath(String attachmentPath) {
		this.attachmentPath = attachmentPath;
	}

}
