package edu.unbosque.model;

// Generated 8/04/2013 03:56:28 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Semillerosocial generated by hbm2java
 */
@Entity
@Table(name = "semillerosocial", catalog = "semillero")
public class Semillerosocial implements java.io.Serializable {

	private int idSemilleroSocial;
	private Socialstatus socialstatus;
	private Date creationDate;
	private Set<Semilleros> semilleroses = new HashSet<Semilleros>(0);

	public Semillerosocial() {
	}

	public Semillerosocial(int idSemilleroSocial, Socialstatus socialstatus,
			Date creationDate) {
		this.idSemilleroSocial = idSemilleroSocial;
		this.socialstatus = socialstatus;
		this.creationDate = creationDate;
	}

	public Semillerosocial(int idSemilleroSocial, Socialstatus socialstatus,
			Date creationDate, Set<Semilleros> semilleroses) {
		this.idSemilleroSocial = idSemilleroSocial;
		this.socialstatus = socialstatus;
		this.creationDate = creationDate;
		this.semilleroses = semilleroses;
	}

	@Id
	@Column(name = "id_semilleroSocial", unique = true, nullable = false)
	public int getIdSemilleroSocial() {
		return this.idSemilleroSocial;
	}

	public void setIdSemilleroSocial(int idSemilleroSocial) {
		this.idSemilleroSocial = idSemilleroSocial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SocialStatus_id_socialStatus", nullable = false)
	public Socialstatus getSocialstatus() {
		return this.socialstatus;
	}

	public void setSocialstatus(Socialstatus socialstatus) {
		this.socialstatus = socialstatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creationDate", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "semilleros_has_semillerosocial", catalog = "semillero", joinColumns = { @JoinColumn(name = "SemilleroSocial_id_semilleroSocial", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Semilleros_id_semillero", nullable = false, updatable = false) })
	public Set<Semilleros> getSemilleroses() {
		return this.semilleroses;
	}

	public void setSemilleroses(Set<Semilleros> semilleroses) {
		this.semilleroses = semilleroses;
	}

}
