package edu.unbosque.model;

// Generated 8/04/2013 03:56:28 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Semilleroschedule generated by hbm2java
 */
@Entity
@Table(name = "semilleroschedule", catalog = "semillero")
public class Semilleroschedule implements java.io.Serializable {

	private int idSemilleroSchedule;
	private Semilleros semilleros;
	private String name;
	private Date creationDate;
	private String description;
	private Set<Semilleroscheludeitems> semilleroscheludeitemses = new HashSet<Semilleroscheludeitems>(
			0);

	public Semilleroschedule() {
	}

	public Semilleroschedule(int idSemilleroSchedule, Semilleros semilleros) {
		this.idSemilleroSchedule = idSemilleroSchedule;
		this.semilleros = semilleros;
	}

	public Semilleroschedule(int idSemilleroSchedule, Semilleros semilleros,
			String name, Date creationDate, String description,
			Set<Semilleroscheludeitems> semilleroscheludeitemses) {
		this.idSemilleroSchedule = idSemilleroSchedule;
		this.semilleros = semilleros;
		this.name = name;
		this.creationDate = creationDate;
		this.description = description;
		this.semilleroscheludeitemses = semilleroscheludeitemses;
	}

	@Id
	@Column(name = "id_semilleroSchedule", unique = true, nullable = false)
	public int getIdSemilleroSchedule() {
		return this.idSemilleroSchedule;
	}

	public void setIdSemilleroSchedule(int idSemilleroSchedule) {
		this.idSemilleroSchedule = idSemilleroSchedule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Semilleros_id_semillero", nullable = false)
	public Semilleros getSemilleros() {
		return this.semilleros;
	}

	public void setSemilleros(Semilleros semilleros) {
		this.semilleros = semilleros;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "semilleroschedule")
	public Set<Semilleroscheludeitems> getSemilleroscheludeitemses() {
		return this.semilleroscheludeitemses;
	}

	public void setSemilleroscheludeitemses(
			Set<Semilleroscheludeitems> semilleroscheludeitemses) {
		this.semilleroscheludeitemses = semilleroscheludeitemses;
	}

}
