package edu.unbosque.model;

// Generated 8/04/2013 03:56:28 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Semilleroscheludeitems generated by hbm2java
 */
@Entity
@Table(name = "semilleroscheludeitems", catalog = "semillero")
public class Semilleroscheludeitems implements java.io.Serializable {

	private int idSemilleroScheludeItems;
	private Semilleroschedule semilleroschedule;
	private Date to;
	private Date from;
	private String desc;
	private String label;
	private String dataObj;

	public Semilleroscheludeitems() {
	}

	public Semilleroscheludeitems(int idSemilleroScheludeItems,
			Semilleroschedule semilleroschedule, Date to, Date from,
			String desc, String label, String dataObj) {
		this.idSemilleroScheludeItems = idSemilleroScheludeItems;
		this.semilleroschedule = semilleroschedule;
		this.to = to;
		this.from = from;
		this.desc = desc;
		this.label = label;
		this.dataObj = dataObj;
	}

	@Id
	@Column(name = "id_semilleroScheludeItems", unique = true, nullable = false)
	public int getIdSemilleroScheludeItems() {
		return this.idSemilleroScheludeItems;
	}

	public void setIdSemilleroScheludeItems(int idSemilleroScheludeItems) {
		this.idSemilleroScheludeItems = idSemilleroScheludeItems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SemilleroSchedule_id_semilleroSchedule", nullable = false)
	public Semilleroschedule getSemilleroschedule() {
		return this.semilleroschedule;
	}

	public void setSemilleroschedule(Semilleroschedule semilleroschedule) {
		this.semilleroschedule = semilleroschedule;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "to", nullable = false, length = 19)
	public Date getTo() {
		return this.to;
	}

	public void setTo(Date to) {
		this.to = to;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "from", nullable = false, length = 19)
	public Date getFrom() {
		return this.from;
	}

	public void setFrom(Date from) {
		this.from = from;
	}

	@Column(name = "desc", nullable = false, length = 100)
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Column(name = "label", nullable = false, length = 45)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "dataObj", nullable = false, length = 100)
	public String getDataObj() {
		return this.dataObj;
	}

	public void setDataObj(String dataObj) {
		this.dataObj = dataObj;
	}

}
