package edu.unbosque.model;

// Generated 8/04/2013 03:56:28 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Socialstatus generated by hbm2java
 */
@Entity
@Table(name = "socialstatus", catalog = "semillero")
public class Socialstatus implements java.io.Serializable {

	private int idSocialStatus;
	private String name;
	private Set<Semillerosocial> semillerosocials = new HashSet<Semillerosocial>(
			0);

	public Socialstatus() {
	}

	public Socialstatus(int idSocialStatus, String name) {
		this.idSocialStatus = idSocialStatus;
		this.name = name;
	}

	public Socialstatus(int idSocialStatus, String name,
			Set<Semillerosocial> semillerosocials) {
		this.idSocialStatus = idSocialStatus;
		this.name = name;
		this.semillerosocials = semillerosocials;
	}

	@Id
	@Column(name = "id_socialStatus", unique = true, nullable = false)
	public int getIdSocialStatus() {
		return this.idSocialStatus;
	}

	public void setIdSocialStatus(int idSocialStatus) {
		this.idSocialStatus = idSocialStatus;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "socialstatus")
	public Set<Semillerosocial> getSemillerosocials() {
		return this.semillerosocials;
	}

	public void setSemillerosocials(Set<Semillerosocial> semillerosocials) {
		this.semillerosocials = semillerosocials;
	}

}
