package edu.unbosque.model;

// Generated 8/04/2013 03:56:28 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", catalog = "semillero")
public class Users implements java.io.Serializable {

	private Integer idUser;
	private Programs programs;
	private Status status;
	private String name;
	private String lastname;
	private String login;
	private String password;
	private String email;
	private Set<News> newses = new HashSet<News>(0);
	private Set<Semilleros> semilleroses = new HashSet<Semilleros>(0);
	private Set<Semilleros> semilleroses_1 = new HashSet<Semilleros>(0);
	private Set<Semilleros> semilleroses_2 = new HashSet<Semilleros>(0);
	private Set<Messages> messageses = new HashSet<Messages>(0);
	private Set<Groups> groupses = new HashSet<Groups>(0);

	public Users() {
	}

	public Users(String name, String login, String password, String email) {
		this.name = name;
		this.login = login;
		this.password = password;
		this.email = email;
	}

	public Users(Programs programs, Status status, String name,
			String lastname, String login, String password, String email,
			Set<News> newses, Set<Semilleros> semilleroses,
			Set<Semilleros> semilleroses_1, Set<Semilleros> semilleroses_2,
			Set<Messages> messageses, Set<Groups> groupses) {
		this.programs = programs;
		this.status = status;
		this.name = name;
		this.lastname = lastname;
		this.login = login;
		this.password = password;
		this.email = email;
		this.newses = newses;
		this.semilleroses = semilleroses;
		this.semilleroses_1 = semilleroses_1;
		this.semilleroses_2 = semilleroses_2;
		this.messageses = messageses;
		this.groupses = groupses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_user", unique = true, nullable = false)
	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Programs_Faculties_id_faculty")
	public Programs getPrograms() {
		return this.programs;
	}

	public void setPrograms(Programs programs) {
		this.programs = programs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Status_id_status")
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "lastname", length = 45)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "login", nullable = false, length = 25)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", nullable = false, length = 40)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<News> getNewses() {
		return this.newses;
	}

	public void setNewses(Set<News> newses) {
		this.newses = newses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "leaders_by_semillero", catalog = "semillero", joinColumns = { @JoinColumn(name = "Users_id_user", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Semilleros_id_semillero", nullable = false, updatable = false) })
	public Set<Semilleros> getSemilleroses() {
		return this.semilleroses;
	}

	public void setSemilleroses(Set<Semilleros> semilleroses) {
		this.semilleroses = semilleroses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "students_by_semillero", catalog = "semillero", joinColumns = { @JoinColumn(name = "Users_id_user", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Semilleros_id_semillero", nullable = false, updatable = false) })
	public Set<Semilleros> getSemilleroses_1() {
		return this.semilleroses_1;
	}

	public void setSemilleroses_1(Set<Semilleros> semilleroses_1) {
		this.semilleroses_1 = semilleroses_1;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "teaching_by_semillero", catalog = "semillero", joinColumns = { @JoinColumn(name = "Users_id_user", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Semilleros_id_semillero", nullable = false, updatable = false) })
	public Set<Semilleros> getSemilleroses_2() {
		return this.semilleroses_2;
	}

	public void setSemilleroses_2(Set<Semilleros> semilleroses_2) {
		this.semilleroses_2 = semilleroses_2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Messages> getMessageses() {
		return this.messageses;
	}

	public void setMessageses(Set<Messages> messageses) {
		this.messageses = messageses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "groups_has_users", catalog = "semillero", joinColumns = { @JoinColumn(name = "Users_id_user", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "Groups_id_group", nullable = false, updatable = false) })
	public Set<Groups> getGroupses() {
		return this.groupses;
	}

	public void setGroupses(Set<Groups> groupses) {
		this.groupses = groupses;
	}

}
